INSERT INTO public.answers (id_question,description,correct) VALUES
	 (1,'Apenas I',true),
	 (1,'Apenas II',false),
	 (1,'Apenas I e II',false),
	 (1,'Apenas III e IV',false),
	 (2,'É dever do profissional de enfermagem aplicar o processo de enfermagem como instrumento metodológico para planejar, implementar, avaliar e documentar o cuidado à pessoa',false),
	 (2,'As infrações são consideradas leves, moderadas, graves ou gravíssimas, segundo a natureza do ato e a circunstância de cada caso',true),
	 (2,'O enfermeiro com especializações comprovadas tem autonomia para prescrever medicações quando o médico solicita por telefone',false),
	 (2,'Todos os profissionais de enfermagem têm a obrigação de uma vez ao ano manter os dados cadastrais atualizados junto ao Conselho Regional de Enfermagem de sua jurisdição',false),
	 (3,'Promover orientação aos pacientes na pós-consulta quanto ao cumprimento das prescrições de cuidados de enfermagem e prescrições médicas',false),
	 (3,'Prescrição de medicamentos de programas específicos do Ministério da Saúde',true);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (3,'Cuidados diretos aos pacientes gravemente enfermos, e que apresentam risco de morte iminente',false),
	 (3,'Ações de Vigilância Epidemiológica, como notificação e investigação de agravos de notificação compulsória',false),
	 (4,'Enfermeiro, Auxiliar de enfermagem e Técnico de enfermagem',false),
	 (4,'Enfermeiro, Auxiliar de enfermagem, Técnico de enfermagem e Parteira',true),
	 (4,'Enfermeiro, Auxiliar de enfermagem, Técnico de enfermagem e Agente Comunitário de Saúde',false),
	 (4,'Enfermeiro, Técnico de enfermagem e Parteira',false),
	 (5,'O Planejamento de Enfermagem é a determinação dos resultados que se espera alcançar; e das ações ou intervenções de enfermagem que serão realizadas face às respostas da pessoa, família ou coletividade humana em um dado momento do processo saúde e doença, identificadas na etapa de Diagnóstico de Enfermagem',true),
	 (5,'O Processo de Enfermagem deve ser realizado, de modo deliberado e sistemático, sendo obrigatório apenas nos ambientes públicos em que ocorre o cuidado profissional de Enfermagem',false),
	 (5,'O diagnóstico de enfermagem é definido como um processo deliberado, sistemático e contínuo de verificação de mudanças nas respostas do indivíduo, da família ou da comunidade em um dado momento',false),
	 (5,'A avaliação de enfermagem é o julgamento clínico sobre as respostas humanas reais ou potenciais apresentadas por indivíduos, famílias e comunidades a problemas de saúde ou processos de vida',false);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (6,'Aproveitar-se da fragilidade da vítima',true),
	 (6,'Realizar atos sob coação e/ou intimidação ou grave ameaça',false),
	 (6,'Ter colaborado espontaneamente com a elucidação dos fatos',false),
	 (6,'Ter confessado espontaneamente a autoria da infração',false),
	 (7,'Assumir e prestar assistência de maior complexidade técnica à pacientes graves e com risco de vida, que exijam conhecimentos científicos adequados e capacidade de tomar decisões imediatas. ',true),
	 (7,'Reportar o caso para CRU (Central de Regulação às Urgências) e seguir orientações/determinações do Médico Regulador (MR)',false),
	 (7,'Prestar assistência segura aos pacientes, zelando pela sua integridade física e psíquica',false),
	 (7,'Preencher ficha de atendimento de maneira completa, objetiva e com letra legível, deixando uma via no local onde o paciente for entregue',false),
	 (8,'Luvas, avental/capote, máscara cirúrgica, óculos/protetor facial',false),
	 (8,'Luvas, óculos/protetor facial, máscara cirúrgica, avental/capote',false);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (8,'Máscara cirúrgica, óculos/protetor facial, avental/capote, luvas',false),
	 (8,'Avental/capote, máscara cirúrgica, óculos/protetor facial, luvas',true),
	 (9,'Troca de paciente',false),
	 (9,'Atraso no horário de administração',false),
	 (9,'Avaliação prévia do paciente',true),
	 (9,'Alteração do tempo de infusão',false),
	 (10,'Apenas I',false),
	 (10,'Apenas II',true),
	 (10,'Apenas I e III',false),
	 (10,'Apenas II e IV',false);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (11,'Privativamente ao enfermeiro, o diagnóstico de enfermagem, bem como a prescrição das ações ou intervenções de enfermagem',true),
	 (11,'Privativamente ao enfermeiro, apenas a prescrição das ações e intervenções de enfermagem',false),
	 (11,'Privativamente ao técnico e auxiliar de enfermagem, a prescrição das ações e intervenções de enfermagem',false),
	 (11,'Privativamente ao enfermeiro, a execução do Processo de Enfermagem',false),
	 (12,'V – F – F',false),
	 (12,'F – V – V',true),
	 (12,'V – V – V',false),
	 (12,'F – V – F',false),
	 (13,'Enfermeiro',false),
	 (13,'Técnico de Enfermagem',false);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (13,'Auxiliar de Enfermagem',true),
	 (13,'Parteira',false),
	 (15,'Apenas o item I está certo',false),
	 (15,'Apenas o item III está certo',false),
	 (15,'Apenas os itens II e III estão certos',false),
	 (15,'Todos os itens estão certos',true),
	 (16,'A todos os conselhos regionais é facultada a criação de cargos de vice-presidente, segundo-secretário e segundo-tesoureiro',false),
	 (16,'O COFEN e os conselhos regionais de enfermagem são órgãos disciplinadores do exercício da profissão, devendo haver um conselho regional em cada estado ou território. Entretanto, em unidades federativas com menos de cinquenta profissionais habilitados, o COFEN poderá determinar a formação de regiões, compreendendo mais de uma unidade',true),
	 (16,'Os conselhos regionais serão instalados em suas respectivas sedes, com 5 a 21 membros e seus suplentes, em uma proporção de três quintos de enfermeiros e dois quintos de profissionais das demais categorias de pessoal de enfermagem reguladas pela lei. Todavia, o número de membros sempre será ímpar e a fixação definida por delegados regionais',false),
	 (16,'Membros do COFEN e dos conselhos regionais têm mandato de três anos de duração. Porém, o processo eleitoral do COFEN é realizado por meio de voto pessoal secreto e obrigatório, e o dos conselhos regionais, por meio de assembleia dos delegados regionais',false);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (14,'No Código de Ética dos Profissionais de Enfermagem, no capítulo das proibições.',false),
	 (14,'No Código de Ética dos Profissionais de Enfermagem, no capítulo dos deveres',true),
	 (14,'Na Lei do Exercício Profissional, no capítulo das atividades do trabalho em equipe',false),
	 (19,'Uma organização da sociedade civil de interesse público',false),
	 (19,'Uma fundação',false),
	 (19,'Uma autarquia',false),
	 (19,'Um conjunto de associações sem fins econômicos',false),
	 (20,'Participação no planejamento, na execução e na avaliação de saúde',false),
	 (20,'Prescrição de medicamentos previamente estabelecidos em programas de saúde pública e em rotina aprovada pelo município',false),
	 (20,'Organização, planejamento, coordenação, execução e avaliação dos serviços da assistência de enfermagem, organização e direção dos serviços de enfermagem',true);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (20,'Participação em programas e atividades de educação sanitária, visando à melhoria de saúde do indivíduo, da família e da população em geral',false),
	 (14,'Na Lei do Exercício Profissional, no artigo das atividades do técnico de Enfermagem',false),
	 (17,'Dever profissional participar em movimentos reivindicatórios da categoria',false),
	 (17,'Permitido delegar a acompanhantes dos pacientes atribuições de profissionais de enfermagem em alguns casos de atenção domiciliar',false),
	 (17,'Facultado ao profissional comunicar externamente caso de violência contra idoso',false),
	 (17,'Obrigatório ao profissional identificar as instituições envolvidas quando publicar resultados de suas pesquisas',true),
	 (18,'Entidades de direito privado que mantenham atividades de formação de recursos humanos em enfermagem devem se registrar no Conselho Regional de Enfermagem local',false),
	 (18,'Enfermeiros podem participar de projetos de construção de unidades de internação',true),
	 (18,'Apenas enfermeiros podem coordenar cursos para formação de recursos humanos em enfermagem',false),
	 (18,'Titulares de diplomas estrangeiros em enfermagem, ainda que revalidados no Brasil, não podem ser considerados enfermeiros',false);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (21,'de acordo com os direitos previstos no Código de Ética de Enfermagem',true),
	 (21,'em desacordo com os deveres de um profissional de enfermagem',false),
	 (21,'de forma negligente, pois deixou de cumprir seu dever profissional',false),
	 (21,'com imprudência, pois desobedeceu as orientações do Conselho Federal de Enfermagem',false),
	 (22,'Atinja a profissão',true),
	 (22,'Sustentem a prática profissional',false),
	 (22,'Fundamentem o profissional',false),
	 (22,'Imponham risco à saúde pública',false),
	 (23,'a punição foi arbitrária, pois, a suspensão não pode ultrapassar 30 dias',false),
	 (23,'a punição está dentro do que determina o Código de Ética de Enfermagem',true);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (23,'o Código de Ética não prevê a retenção da carteira em caso de suspensão',false),
	 (23,'a suspensão máxima prevista no Código de Ética de Enfermagem é de 45 dias',false),
	 (24,'Participação na elaboração, execução e avaliação dos planos assistenciais de saúde',false),
	 (24,'Planejamento, organização, coordenação, execução e avaliação dos serviços da assistência de Enfermagem',true),
	 (24,'Prevenção e controle sistemático da infecção hospitalar, inclusive como membro das respectivas comissões',false),
	 (24,'Participação no planejamento, execução e avaliação da programação de saúde',false),
	 (25,'Leve',false),
	 (26,'F – V – V',false),
	 (26,'V – V – F',false),
	 (25,'Grave',true);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (25,'Simples',false),
	 (25,'moderada',true),
	 (26,'F – F – V',true),
	 (26,'V – F – F',false),
	 (27,'A multa consiste na obrigatoriedade de pagamento de até 12 vezes o valor da anuidade da categoria profissional do infrator',false),
	 (27,'É um dever do profissional de enfermagem denunciar atos de violência contra idosos, independentemente de autorização',true),
	 (27,'Um profissional de enfermagem suspenso pode ser proibido de exercer a profissão por um período de até 120 dias',false),
	 (27,'Quando o profissional de enfermagem deixa de cumprir, no prazo estabelecido, convocações e intimações do Coren, ele está sujeito à penalidade de censura',false),
	 (28,'3 pacientes',false),
	 (28,'4 pacientes',false);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (28,'6 pacientes',true),
	 (28,'10 pacientes',false),
	 (29,'I',false),
	 (29,'III',false),
	 (29,'I e II',true),
	 (29,'II e III',false),
	 (30,'fazer prescrição da assistência de enfermagem',false),
	 (30,'realizar cuidados diretos de enfermagem a pacientes graves',true),
	 (30,'realizar testes e proceder à sua leitura, para subsídio de diagnóstico',false),
	 (30,'prestar assistência à parturiente e ao parto normal',false);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (31,'em caso de falecimento da pessoa envolvida',false),
	 (31,'quando o fato é de conhecimento público',false),
	 (31,'em caso de violência doméstica contra mulher adulta',true),
	 (31,'quando o profissional de enfermagem é intimado como testemunha',false),
	 (32,'relacionado ao não cumprimento do dever do profissional em respeitar a intimidade da pessoa sob seus cuidados',true),
	 (32,'produzido por dano moral e social ao paciente que está sob seus cuidados',false),
	 (32,'relacionado ao não cumprimento das regras de silêncio no espaço hospitalar',false),
	 (32,'suscitado pela circulação e disseminação de informação com outro profissional fora da equipe de enfermagem',false),
	 (33,'máximo de 6 meses',false),
	 (33,'de até 90 dias',true);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (33,'de até 9 meses',false),
	 (33,'de até 1 ano',false),
	 (34,'realizar foto-documentação para avaliação pelo enfermeiro da evolução da ferida',false),
	 (34,'executar o desbridamento mecânico ou instrumental quando prescrito pelo médico',false),
	 (34,'registrar no prontuário do paciente as características da ferida e suas queixas',true),
	 (34,'avaliar as características e a evolução da ferida e indicar o tipo de cobertura para tratamento',false),
	 (35,'ausentar-se do serviço durante o expediente, sem prévia autorização do superior imediato',false),
	 (35,'apresentar falta ao serviço, por vinte dias, interpoladamente, sem causa justificada, no período de seis meses',false),
	 (35,'abandonar o cargo, caracterizando-se o abandono pela ausência injustificada, por mais de trinta dias consecutivos',false),
	 (35,'praticar comércio de compra e venda de bens ou serviços no recinto da repartição, ainda que fora do horário normal de expediente',true);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (36,'manter o registro dos profissionais com exercício na respectiva jurisdição',true),
	 (36,'baixar provimentos e expedir instruções para uniformidade de procedimentos',false),
	 (36,'instituir o modelo das carteiras profissionais de identidade e as insígnias da profissão',false),
	 (36,'promover estudos e campanhas para aperfeiçoamento profissional de seus colaboradores',false),
	 (37,'obrigatório o uso de carimbo e deve conter o nome completo, o número e categoria de inscrição no COFEN',false),
	 (37,'obrigatória, na assinatura digital, em atenção às normas de segurança, a impressão dos documentos para guarda e manuseio',false),
	 (37,'facultativo o registro do histórico e do diagnóstico de enfermagem, sendo obrigatória a evolução de enfermagem',false),
	 (37,'permitido o uso da assinatura digital, pois ela garante a autenticidade de arquivos eletrônicos e é tipicamente tratada como análoga à assinatura física em papel',true),
	 (38,'proceder os testes para confirmação do trajeto da sonda',false),
	 (38,'estabelecer o acesso enteral por via oro/nasogástrica para drenar líquidos',false);
INSERT INTO public.answers (id_question,description,correct) VALUES
	 (38,'promover cuidados gerais ao paciente de acordo com o protocolo pré-estabelecido',true),
	 (38,'garantir a troca da sonda conforme pré-estabelecido pela Comissão de Controle de Infecção Hospitalar (CCIH) da instituição',false),
	 (39,'realizar cateterismo vesical, conforme prescrição médica',false),
	 (39,'prestar cuidados diretos a pacientes graves com risco de vida',false),
	 (39,'assistir o enfermeiro na prevenção e no controle de doenças transmissíveis',true),
	 (39,'participar da operacionalização do sistema de referência e contrarreferência do paciente nos diferentes níveis de atenção à saúde',false),
	 (40,'graves, submetidos à intubação orotraqueal, em unidade de terapia intensiva, quando prescrito pelo enfermeiro',false),
	 (40,'estáveis e sem respiração artificial, em unidade intensiva, semi-intensiva, de internação e de urgência, e na ausência do enfermeiro',false),
	 (40,'graves e sem respiração artificial, em unidade de emergência, com posterior comunicação ao enfermeiro, para prescrição do cuidado realizado anteriormente',false),
	 (40,'crônicos, em uso de traqueostomia definitiva, no atendimento ambulatorial, quando avaliado e prescrito pelo enfermeiro',true);
