INSERT INTO public.questions (description) VALUES
	 ('A paramentação é o conjunto de barreiras contra microorganismos com a finalidade de proteger os profissionais de saúde em meio à atuação. <br>Qual a sequência correta da paramentação recomendada para precaução de contato e gotículas, de acordo com a cartilha do COFEN?'),
	 ('Analise o trecho a seguir, referente à lei que regulamenta a prática da Enfermagem:  <br>"[...] exerce as atividades de nível médio, de natureza repetitiva, envolvendo serviços auxiliares de Enfermagem sob supervisão, bem como a participação em nível de execução simples, em processos de tratamento".<br> As atribuições descritas nesse trecho são referentes a qual categoria profissional?'),
	 ('Considere  que um profissional de enfermagem tenha sido responsável por fotografar e divulgar imagens que identificam um paciente sem autorização expressa da instituição e dos familiares ou do próprio paciente. Nesse caso, ele estaria descumprindo uma orientação prevista'),
	 ('Conforme regulamentação da legislação sobre o exercício da Enfermagem, Lei 7498/86, é atribuição exclusiva do Enfermeiro'),
	 ('De acordo com a Lei N° 7.498/86, a Enfermagem é exercida privativamente pelos seguintes profissionais'),
	 ('A Resolução do Cofen 358/2009 dispõe sobre a Sistematização da Assistência de Enfermagem e a implementação do Processo de Enfermagem.  Sobre esse tema, é correto afirmar'),
	 ('Com base na Ética Profissional - Resolução COFEN 564/2017, assinale a alternativa CORRETA que é considerada circunstância agravante'),
	 ('O SAMU é um serviço gratuito, que funciona 24 horas, por meio da prestação de orientações e do envio de veículos tripulados por equipe capacitada, acessado pelo número 192 e acionado por uma Central de Regulação das Urgências. Dentro da equipe multidisciplinar, são atribuições do Técnico de Enfermagem, EXCETO'),
	 ('A Resolução do Cofen nº 358/2009 dispõe sobre a Sistematização da Assistência de Enfermagem e a implementação do Processo de Enfermagem baseado em um suporte teórico que oriente a coleta de dados, o estabelecimento de diagnóstico e o planejamento de ações e intervenções de Enfermagem, que forneça a base para a avaliação dos resultados de enfermagem alcançados e ainda prevê'),
	 ('Com base na legislação nacional que regulamenta o exercício da enfermagem, é correto afirmar que ');
INSERT INTO public.questions (description) VALUES
	 ('Apenas uma das situações abaixo NÃO constitui erro cometido por profissionais de enfermagem durante a administração de medicamentos. <br>Assinale-a'),
	 ('De acordo com os dispositivos que regulam direitos e obrigações de profissionais de enfermagem, é correto afirmar que é '),
	 ('Com relação ao Conselho Federal de Enfermagem (COFEN) e aos conselhos regionais de enfermagem, assinale a opção correta'),
	 ('Conforme o novo  Código de Ética da  Enfermagem, resolução Cofen nº 564/2017. <br>Assinale a alternativa correta'),
	 ('A Resolução COFEN nº 564/2017 instituiu o novo Código de Ética dos Profissionais de Enfermagem. Considere os itens a seguir.  <br>I - Ter acesso às informações relacionadas a pessoa, família e coletividade, necessárias ao exercício profissional.  <br>II - Administrar medicamentos sem conhecer indicação, ação da droga, via de administração e potenciais riscos, respeitados os graus de formação do profissional.  <br>III- Abster-se de revelar informações confidenciais de que tenha conhecimento em razão de seu exercício profissional. <br> IV - Prestar assistência de Enfermagem sem discriminação de qualquer natureza.  <br>Quais estão presentes no capítulo Das Proibições do Código de Ética dos Profissionais de Enfermagem?'),
	 ('Considerando as disposições do Código de Ética de Enfermagem, analise as afirmativas a seguir e assinale (V) para verdadeira e (F) para a falsa.  <br>(  ) Quando uma falta for praticada em equipe, a responsabilidade será atribuída igualmente a todos os membros que participaram do ato. <br>(  ) O profissional de Enfermagem tem o dever de manter sigilo sobre fato de que tenha conhecimento em razão da atividade profissional, mesmo quando esse fato for de conhecimento público.  <br>(  ) As penalidades previstas no Código de Ética somente poderão ser aplicadas cumulativamente, quando houver infração a mais de um artigo. <br>As afirmativas são, na ordem apresentada, respectivamente'),
	 ('Toda lei do exercício profissional, de uma forma geral, atende necessidades elementares da institucionalização de uma profissão, a delimitação de seu campo de trabalho e a definição jurídica de sua identidade profissional. Referente à regulamentação do exercício da enfermagem, analise as assertivas abaixo:
   <br>I. Ao profissional enfermeiro incumbe privativamente realizar consultoria, auditoria e emissão de parecer sobre matéria de enfermagem.
   <br>II. Ao profissional enfermeiro incumbe privativamente prestar cuidados à gestante e à parturiente.
   <br>III. É privativo do enfermeiro a prescrição de medicamentos previamente estabelecidos em programas de saúde pública.
   <br>IV. Incumbe a todo o pessoal de enfermagem a realização da consulta de enfermagem.
<br>Quais estão corretas?'),
	 ('A resolução que dispõe sobre o exercício da enfermagem define as atividades que o técnico de enfermagem exerce. É uma função desse profissional'),
	 ('Segundo o código de ética dos profissionais de enfermagem é um dever manter sigilo sobre fato de que tenha conhecimento em razão da atividade profissional, exceto nos casos previstos na legislação. Levando em consideração os dados apresentados, NÃO se deve manter sigilo'),
	 ('No que se refere ao código de ética que deve ser seguido por todos os profissionais de enfermagem, julgue os itens que se seguem. <br>I Diante de situação em que houver risco à sua integridade física e moral, como assédio sexual, é direito do profissional de enfermagem requerer a seu gestor a quebra de vínculo da relação profissional/usuário.  <br>II Todo profissional de enfermagem tem o dever de posicionar-se contra ações e procedimentos de membros da equipe de saúde que possam acarretar danos decorrentes de imperícia, negligência e imprudência ao paciente, devendo denunciar a órgãos competentes. <br>III É dever do profissional de enfermagem manter sigilo sobre fato de que tenha conhecimento em razão da atividade profissional, mesmo se o fato vier a conhecimento público. Entretanto, torna-se obrigatória a comunicação para órgãos de responsabilização criminal, em casos de violência contra crianças e adolescentes, idosos e pessoas incapacitadas, independentemente de autorização. <br>Assinale a opção correta');
INSERT INTO public.questions (description) VALUES
	 ('O sistema formado pelo Conselho Federal de Enfermagem (COFEN) e pelos conselhos regionais de enfermagem (COREN) é'),
	 ('O exercício profissional da enfermagem, assegurado pelo Decreto nº 94.406/1987, é regulamentado pela Lei nº 7.498/1986. Entre as atividades privativas da supervisão de enfermagem, estão'),
	 ('Durante um plantão, o técnico de enfermagem recusou-se a praticar determinada atividade, alegando não ter competência técnico-científica nem respaldo legal. Nesse caso, o profissional agiu'),
	 ('De acordo com o Código de Ética dos Profissionais de Enfermagem (CEPE) é direito dos profissionais de enfermagem requerer ao Conselho Regional de Enfermagem, de forma fundamentada, medidas cabíveis para obtenção de desagravo público em decorrência de ofensa sofrida, no exercício profissional ou que'),
	 ('Um enfermeiro foi punido com suspensão de 50 dias e teve sua carteira profissional retida no ato da notificação. Considerando o que dispõe o Código de Ética, é correto afirmar que'),
	 ('Assinale a opção que indica uma função privativa do enfermeiro'),
	 ('Ao saber mais sobre ética profissional, o enfermeiro poderá seguir as diretrizes adequadas para que as atividades de enfermagem sejam seguras para o paciente e para o profissional. Durante as ações de cuidado, e durante a visita de familiares, no corredor do hospital, uma enfermeira conversa com um colega do serviço social sobre questões privadas de um paciente internado. Esta atitude é percebida como um problema ético'),
	 ('O profissional de Enfermagem, que comete uma infração punível com suspensão, fica proibido de exercer a profissão por um período'),
	 ('Devido a um ato de negligência do profissional de enfermagem, um paciente sofreu debilidade temporária do membro inferior direito.<br>De acordo com o Código de Ética, a infração cometida é considerada
'),
	 ('Sobre a atuação do Enfermeiro Auditor, disposta em Resolução do COFEN, analise as afirmativas a seguir e assinale (V) para a verdadeira e (F) para a falsa.<br>( ) Na função de auditor, o enfermeiro pode interferir nos registros do prontuário do paciente. .<br>( ) O enfermeiro deve exercer a função de auditoria sempre acompanhado de outro profissional. .<br>( ) Na função de auditor, o enfermeiro tem direito a acessar o prontuário do paciente e toda documentação pertinente. .<br>As afirmativas são, na ordem apresentada, respectivamente');
INSERT INTO public.questions (description) VALUES
	 ('Acerca das disposições do Código de Ética de Enfermagem, é correto afirmar que'),
	 ('Conforme dimensionamento recomendado pelo COFEN, uma unidade de saúde que presta assistência classificada como cuidados mínimos, deve manter, nos diferentes turnos de trabalho, a proporção de 1 profissional de enfermagem para cada'),
	 ('Com base nas normativas que norteiam o exercício da enfermagem, analise as afirmativas a seguir.<br>I. O enfermeiro tem autonomia para abertura de clínica de Prevenção e Cuidado de pessoas com feridas, respeitadas as competências técnicas e legais. <br>II. É permitido que o enfermeiro devidamente capacitado realize a inserção de Cateter Periférico Central (PICC). <br>III. A direção dos serviços de enfermagem cabe preferencialmente ao enfermeiro, mas pode ser exercida por outro profissional.<br>Está correto somente o que se afirma em'),
	 ('A Resolução COFEN nº 567/2018 regulamenta a atuação da equipe de enfermagem no cuidado aos pacientes com feridas. De acordo com o anexo dessa Resolução, é competência do técnico de enfermagem'),
	 ('A penalidade disciplinar de suspensão por até 30 (trinta) dias será aplicada ao empregado público que, segundo o anexo do Código de Ética dos Empregados Públicos do Sistema COFEN/Conselhos Regionais de Enfermagem (COFEN nº 0507/2016), cometer a seguinte falta administrativa'),
	 ('De acordo com a Lei nº 5.095/1973, é competência dos Conselhos Regionais'),
	 ('É correto afirmar que, segundo as Resoluções Cofen nº 429/2012, Cofen nº 564/2017 e Cofen nº 358/2009 para o registro das ações profissionais no prontuário do paciente, é'),
	 ('É correto afirmar que, considerando a atuação do técnico e/ou auxiliar de enfermagem na sondagem oro/nasoenteral (Resolução COFEN nº 619/2019), é de sua competência'),
	 ('O técnico de enfermagem de uma instituição pública solicita orientação sobre o exercício de suas atividades em uma unidade de clínica cirúrgica. De acordo com o Decreto nº 94.406/1987 que regulamenta a Lei nº 7.498/1986, é função do técnico de enfermagem'),
	 ('O procedimento de aspiração de vias aéreas foi regulamentado no âmbito da equipe de enfermagem pela Resolução COFEN nº 557/2017. É correto afirmar que esse procedimento será realizado pelo técnico de enfermagem em pacientes');
